### ISSUE TITLE
Support full serialization saving as well as data-visualization-compliant saving.

### ISSUE THREAD

**Issue by sezna** [sezna/bigbang#12]
It'd be nice to integrate serde and allow for saving to bincode or json in addition to the data file method currently provided. It could include the time_step as well.

**Comment by sezna** [comment]
This could be accomplished easily by just deriving serialize, serializing to json, and writing a quick transformation script in JS/whatever to output the desired format.

**Comment by Ameobea** [comment]
The power of functional data structures right there
